name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Deploy src to gh-pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Use subtree push to move src to gh-pages
          git checkout master
          git subtree split --prefix src -b gh-pages-branch
          git push -f origin gh-pages-branch:gh-pages
          git branch -D gh-pages-branch
