name: Convert Markdown to PDF

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  generate-pdf:
    runs-on: ubuntu:24.04

    steps:
      # Checkout the repository to access the markdown file
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-recommended texlive-fonts-recommended pandoc-citeproc

      # Convert Markdown to PDF
      - name: Convert Markdown to PDF
        run: |
          pandoc --citeproc --bibliography=docs/references.bib --to pdf --output docs/riport.pdf --standalone --resource-path=docs docs/riport.md --csl=docs/ieee.csl

      # Upload the PDF as an artifact
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: riport
          path: docs/riport.pdf
